version: '3'

services:
  server:
    build: ../
    entrypoint: ./.docker/entrypoint.sh
    container_name: server
    environment:
      NODE_ENV: local
    ports:
      - 4000:4000
    volumes:
      - ${PWD}/:/home/node/app 
    networks:
      - axur
networks:
  axur:
  
